### ISSUE TITLE
matchengine.py error on the sample data

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-engine#20]
I downloaded examples/mm_data.tar.gz, unzilled it and successfully  loaded into my local mongo:
```
$ mongorestore -d matchminer ~/Downloads/mm_data/matchminer/
2019-01-10T12:38:53.129+0100	building a list of collections to restore from /Users/ipozdnya/Downloads/mm_data/matchminer/ dir
2019-01-10T12:38:53.165+0100	reading metadata file from /Users/ipozdnya/Downloads/mm_data/matchminer/trial.metadata.json
2019-01-10T12:38:53.165+0100	reading metadata file from /Users/ipozdnya/Downloads/mm_data/matchminer/trial_match.metadata.json
2019-01-10T12:38:53.165+0100	reading metadata file from /Users/ipozdnya/Downloads/mm_data/matchminer/clinical.metadata.json
2019-01-10T12:38:53.165+0100	reading metadata file from /Users/ipozdnya/Downloads/mm_data/matchminer/genomic.metadata.json
2019-01-10T12:38:53.180+0100	restoring matchminer.trial from file /Users/ipozdnya/Downloads/mm_data/matchminer/trial.bson
2019-01-10T12:38:53.180+0100	restoring matchminer.trial_match from file /Users/ipozdnya/Downloads/mm_data/matchminer/trial_match.bson
2019-01-10T12:38:53.197+0100	restoring matchminer.genomic from file /Users/ipozdnya/Downloads/mm_data/matchminer/genomic.bson
2019-01-10T12:38:53.197+0100	restoring matchminer.clinical from file /Users/ipozdnya/Downloads/mm_data/matchminer/clinical.bson
2019-01-10T12:38:53.437+0100	restoring indexes for collection matchminer.clinical from metadata
2019-01-10T12:38:53.466+0100	restoring indexes for collection matchminer.genomic from metadata
2019-01-10T12:38:53.527+0100	finished restoring matchminer.genomic (10 documents)
2019-01-10T12:38:53.527+0100	reading metadata file from /Users/ipozdnya/Downloads/mm_data/matchminer/map.metadata.json
2019-01-10T12:38:53.528+0100	finished restoring matchminer.clinical (5 documents)
2019-01-10T12:38:53.528+0100	reading metadata file from /Users/ipozdnya/Downloads/mm_data/matchminer/user.metadata.json
2019-01-10T12:38:53.538+0100	restoring matchminer.map from file /Users/ipozdnya/Downloads/mm_data/matchminer/map.bson
2019-01-10T12:38:53.555+0100	restoring matchminer.user from file /Users/ipozdnya/Downloads/mm_data/matchminer/user.bson
2019-01-10T12:38:53.645+0100	restoring indexes for collection matchminer.trial_match from metadata
2019-01-10T12:38:53.725+0100	finished restoring matchminer.trial_match (25 documents)
2019-01-10T12:38:53.725+0100	reading metadata file from /Users/ipozdnya/Downloads/mm_data/matchminer/status.metadata.json
2019-01-10T12:38:53.738+0100	restoring matchminer.status from file /Users/ipozdnya/Downloads/mm_data/matchminer/status.bson
2019-01-10T12:38:53.811+0100	restoring indexes for collection matchminer.map from metadata
2019-01-10T12:38:53.904+0100	finished restoring matchminer.map (11 documents)
2019-01-10T12:38:53.905+0100	reading metadata file from /Users/ipozdnya/Downloads/mm_data/matchminer/team.metadata.json
2019-01-10T12:38:53.905+0100	restoring matchminer.team from file /Users/ipozdnya/Downloads/mm_data/matchminer/team.bson
2019-01-10T12:38:53.920+0100	restoring indexes for collection matchminer.user from metadata
2019-01-10T12:38:54.141+0100	finished restoring matchminer.user (1 document)
2019-01-10T12:38:54.143+0100	restoring indexes for collection matchminer.status from metadata
2019-01-10T12:38:54.371+0100	finished restoring matchminer.status (1 document)
2019-01-10T12:38:54.426+0100	restoring indexes for collection matchminer.team from metadata
2019-01-10T12:38:54.428+0100	finished restoring matchminer.team (1 document)
2019-01-10T12:38:54.596+0100	restoring indexes for collection matchminer.trial from metadata
2019-01-10T12:38:54.597+0100	finished restoring matchminer.trial (10 documents)
2019-01-10T12:38:54.597+0100	done
```

Now I tried to run the engine:

```
$ python2.7 matchengine.py match --mongo-uri mongodb://localhost:27017
[INFO] Matching trial 00-009
Traceback (most recent call last):
  File "matchengine.py", line 338, in <module>
    args.func(args)
  File "matchengine.py", line 259, in match
    me.find_trial_matches()
  File "/Users/ipozdnya/matchminer-engine/matchengine/engine.py", line 522, in find_trial_matches
    trial_matches = self._assess_match(mrn_map, trial_matches, trial, step, 'step', trial_status)
  File "/Users/ipozdnya/matchminer-engine/matchengine/engine.py", line 582, in _assess_match
    match['mrn'] = mrn_map[alteration['sample_id']]
KeyError: u'04'
```

Should I add some check for key existence or the data needs to be corrected?

**Comment by ethansiegl** [comment]
The demo data is out of date with the current version of the matchengine and needs to be updated.. Currently pending
